version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: 'copy build'
          command: |
            ls -la
            ssh -o StrictHostKeyChecking=no ubuntu@3.232.116.73 'cd /var/www/kaariimashraf && rm -r *'
            scp  -r -o StrictHostKeyChecking=no ./* ubuntu@3.232.116.73:/var/www/kaariimashraf

# Invoke jobs via workflows
workflows:
  say-hello-workflow:
    jobs:
      - deploy
